controllers/ImportController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;
use app\models\ImportForm;

class ImportController extends Controller {

    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'import'],
                        'allow' => true,
                        'roles' => ['import'],
                    ]
                ],
            ]
        ];
    }
    
    public function actionIndex() {
        if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}
		
		$model = new ImportForm();
		
		return $this->render('index', [ 'model' => $model]);
    }
    
    public function actionImport() {
		/*** JSON METHOD ***/
		Yii::$app->response->format = Response::FORMAT_JSON;
		try {
			//se non siamo dentro ad una post, torno all'index
			if (!Yii::$app->request->isPost) throw new Exception ( Yii::t('import','error_invalid_request'));
			
			//creo modulo e carico i dati del form nel modulo
			$model = new ImportForm();
					
			if (!$model->load(Yii::$app->request->post())) throw new Exception( Yii::t('import','error_cannot_load_model') );				
			$model->file = UploadedFile::getInstance($model, 'file');		
			
			//faccio l'upload del file per analizzarlo
			if (!$model->upload()) throw new Exception( Yii::t('import','error_cannot_upload_file') );
			
			//tronco prima la tabella (se richiesto e fattibile)
			$bool = $model->truncate();
			
			//verifico la tipologia di dato e lo carico in mysql
			if (!$model->insert($sql)) throw new Exception( Yii::t('import','error_cannot_import') );
			
			//cancello il file
			$model->removeFile();
			
			return [
				'success' => true,
				'message' => Yii::t('import','success_message') ,
				'query' => $sql
			];
        }
        catch (\Throwable $error) {
			
			//cancello il file
			$model->removeFile();
			
			 return [
				'success' => false, 
				'message' => Yii::t('import','error_cannot_import').': '.$error->getMessage()
			];
		}
	}

}

controllers/PraticaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\bootstrap4\Html;
use app\models\pratica\Pratica;
use app\models\pratica\PraticaSearch;

class PraticaController extends Controller {
	
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['showList'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'view' => ['get'],
                ],
            ],
        ];
    }
    
    //TABELLA
	public function actionIndex() {
		
		if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}
		
		try {
			$praticaSearch = new PraticaSearch();
			$dataProvider = $praticaSearch->search(Yii::$app->request->queryParams);
			$dataProviderAll = $praticaSearch->search();
		} catch (\Throwable $e) {
			throw new \yii\web\ServerErrorHttpException($e->getMessage());
		}
		$columns = $this->getGridColumns();
		
		return $this->render('index',[
			'dataProvider' => $dataProvider, 
			'dataProviderAll' => $dataProviderAll, 
			'praticaSearch' => $praticaSearch,
			'columns' => $columns
		]);
	}
	
	//DETTAGLI
	public function actionView() {
		
		if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}
		
		$id = $this->request->get("id");
		
		try {
			$pratica = Pratica::find()->with('cliente')->where(['id' => $id])->limit(1)->asArray()->one();
		} catch (\Throwable $e) {
			throw new \yii\web\ServerErrorHttpException($e->getMessage());
		}
		
		if (!$pratica) throw new \yii\web\NotFoundHttpException(Yii::t('pratica','error_not_found'));
		
		return $this->render('view', [ 'pratica' => $pratica ]);
	}
	
	//la funzione restituisce le colonne necessarie per la gridView di visualizzazione dei dati e per la loro exportazione
	private function getGridColumns() {
		return [
			[
				'attribute' => 'id',
				'label' => Yii::t('pratica','id'),
				'format' => function($data) {
					return '#'.$data;
				}
			],
			[
				'attribute' => 'id_pratica',
				'label' => Yii::t('pratica','id_pratica'),
			],
			[
				'attribute' => 'data_creazione',
				'label' => Yii::t('pratica','data_creazione'),
				'format' => 'datetime',
				'hidden' => true,
				'hiddenFromExport' => false
			],
			[
				'attribute' => 'stato_pratica',
				'label' => Yii::t('pratica','stato_pratica'),
				'format' => function($data) {
					return Yii::t('pratica',$data);
				}
			],
			[
				'label' => Yii::t('pratica','cliente'),
				'value' => function($model) {
					return ($model['cliente']) ? $model['cliente']['nome'].' '.$model['cliente']['cognome'] : null;
				},
				'hidden' => true,
				'hiddenFromExport' => false
			],
			[
				'label' => Yii::t('pratica','codice_fiscale'),
				'value' =>  function($model) {
					return ($model['cliente']) ? $model['cliente']['codice_fiscale']: null;
				},
				'hidden' => true,
				'hiddenFromExport' => false
			],
			[ 
				'class' => 'kartik\grid\ActionColumn',
				'header' => '',
				'width' => 80,
				'contentOptions' => [ 'class' => 'text-center' ],
				'hiddenFromExport' => true,
				'template' => '{view}',
				'buttons' => [
					'view' => function($url, $model) {
						return Html::a(
							'<i class="fa-solid fa-magnifying-glass-plus"></i>','#',[
								'class' => 'show-details',
								'data-toggle' => 'modal',
								'data-target' => '#details',
								'data-url' => $url
							]
						);
					}
				]
			]
		];
	}
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
		'brandImage' => '@web/images/logo.png',
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark sticky-top',
        ],
        'collapseOptions' => [
			'class' => [ 'text-right flex-grow-0' ]
		]
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
             (Yii::$app->user->can('showList')) ?
				['label' => Yii::t('pratica','page_title'), 'url' => ['/pratica/index']]
					:
				'',
            (Yii::$app->user->can('import')) ?
				['label' => Yii::t('import','page_title'), 'url' => ['/import/index']]
					:
				'',
			(Yii::$app->user->isGuest) ?
                ['label' => Yii::t('site','page_title_login'), 'url' => ['/site/login']]
					:
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline m-0'])
                . Html::submitButton(
                    Yii::t('site','page_title_logout{username}', [ 'username' => Yii::$app->user->identity->username ]),
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>